
-- ============================================
-- E-COMMERCE DATA ANALYSIS PROJECT
-- SQL QUESTIONS & ANSWERS (MySQL)
-- ============================================

-- BASIC PROBLEMS

-- 1. List all unique cities where customers are located
SELECT DISTINCT customer_city
FROM customers;

-- 2. Count the number of orders placed in 2017
SELECT COUNT(*) AS total_orders_2017
FROM orders
WHERE YEAR(order_date) = 2017;

-- 3. Find the total sales per product category
SELECT p.category,
       SUM(oi.price) AS total_sales
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category;

-- 4. Calculate the percentage of orders paid in installments
SELECT 
(COUNT(CASE WHEN payment_installments > 1 THEN 1 END) * 100.0 / COUNT(*)) 
AS installment_percentage
FROM payments;

-- 5. Count the number of customers from each state
SELECT customer_state,
       COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state;

-- ============================================
-- INTERMEDIATE PROBLEMS
-- ============================================

-- 6. Calculate the number of orders per month in 2018
SELECT MONTH(order_date) AS month,
       COUNT(*) AS total_orders
FROM orders
WHERE YEAR(order_date) = 2018
GROUP BY MONTH(order_date)
ORDER BY month;

-- 7. Average number of products per order by customer city
SELECT c.customer_city,
       AVG(order_count) AS avg_products_per_order
FROM (
    SELECT o.order_id,
           c.customer_city,
           COUNT(oi.product_id) AS order_count
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id, c.customer_city
) t
GROUP BY customer_city;

-- 8. Percentage of total revenue contributed by each product category
SELECT p.category,
       SUM(oi.price) * 100 / (SELECT SUM(price) FROM order_items) 
       AS revenue_percentage
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category;

-- 9. Correlation between product price and purchase count (Data Preparation)
SELECT product_id,
       COUNT(*) AS purchase_count,
       AVG(price) AS avg_price
FROM order_items
GROUP BY product_id;

-- 10. Total revenue generated by each seller and ranking
SELECT seller_id,
       SUM(price) AS total_revenue,
       RANK() OVER (ORDER BY SUM(price) DESC) AS seller_rank
FROM order_items
GROUP BY seller_id;

-- ============================================
-- ADVANCED PROBLEMS
-- ============================================

-- 11. Moving average of order value for each customer
SELECT customer_id,
       order_date,
       order_value,
       AVG(order_value) OVER (
           PARTITION BY customer_id
           ORDER BY order_date
           ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
       ) AS moving_average
FROM (
    SELECT o.customer_id,
           o.order_date,
           SUM(oi.price) AS order_value
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id
) t;

-- 12. Cumulative sales per month for each year
SELECT year,
       month,
       SUM(monthly_sales) OVER (
           PARTITION BY year ORDER BY month
       ) AS cumulative_sales
FROM (
    SELECT YEAR(o.order_date) AS year,
           MONTH(o.order_date) AS month,
           SUM(oi.price) AS monthly_sales
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY year, month
) t;

-- 13. Year-over-Year (YoY) growth rate of total sales
SELECT year,
       total_sales,
       LAG(total_sales) OVER (ORDER BY year) AS previous_year_sales,
       ((total_sales - LAG(total_sales) OVER (ORDER BY year)) /
        LAG(total_sales) OVER (ORDER BY year)) * 100 AS yoy_growth
FROM (
    SELECT YEAR(o.order_date) AS year,
           SUM(oi.price) AS total_sales
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY year
) t;

-- 14. Customer retention rate within 6 months
SELECT 
COUNT(DISTINCT o2.customer_id) * 100.0 /
COUNT(DISTINCT o1.customer_id) AS retention_rate
FROM orders o1
LEFT JOIN orders o2
ON o1.customer_id = o2.customer_id
AND o2.order_date > o1.order_date
AND o2.order_date <= DATE_ADD(o1.order_date, INTERVAL 6 MONTH);

-- 15. Top 3 customers who spent the most money in each year
SELECT *
FROM (
    SELECT YEAR(o.order_date) AS year,
           o.customer_id,
           SUM(oi.price) AS total_spent,
           RANK() OVER (
               PARTITION BY YEAR(o.order_date)
               ORDER BY SUM(oi.price) DESC
           ) AS rank_no
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY year, o.customer_id
) t
WHERE rank_no <= 3;

-- ============================================
-- END OF PROJECT SQL FILE
-- ============================================
